power on the server before pxe using ipmitool
JIRA: COMPASS-314

Change-Id: Iff6910412217a7daff3e93370075747abcd3ac38
Signed-off-by: baigk <baiguoku@huawei.com>
(cherry picked from commit 85308a67a409694de2eca3f89ef3fbcc390416a9)

diff --git a/deploy/template/power/ipmitool.tmpl b/deploy/template/power/ipmitool.tmpl
--- a/deploy/template/power/ipmitool.tmpl
+++ b/deploy/template/power/ipmitool.tmpl
@@ -27,7 +27,19 @@ exit 1
 #else
     #set interface='lan'
 #end if
-
+for i in {1..5}; do
+    if ipmitool -I $interface -H $ipmiIp -U $ipmiUser -P $ipmiPass chassis power on >/dev/null 2>&1
+    then
+        break
+    elif [[ i -lt 5 ]]
+    then
+        sleep 1
+    else
+        log_error "$ipmiIp power on fail"
+        exit 1
+    fi
+done
+sleep 1
 for i in {1..5}; do
     if ipmitool -I $interface -H $ipmiIp -U $ipmiUser -P $ipmiPass chassis bootdev pxe >/dev/null 2>&1
     then
